 Console.WriteLine("艾瑞斯驱动安装软件:");
 Console.WriteLine("    索引驱动目录，按需安装本机设备驱动。");
 Console.WriteLine("    至多 10个线程同时 读 写 装。");
 Console.WriteLine("    适用于对 Win10/11/PE x64 当前系统或离线系统 安装驱动");
 Console.WriteLine("    驱动目录默认为 本程序所在目录\\Drivers");
 Console.WriteLine("    注：支持驱动包*.7z，或未压缩的驱动文件");
 Console.WriteLine("");
 Console.WriteLine("参数帮助(参数为小写):");
 Console.WriteLine("    /auto            自动索引驱动，自动安装驱动。");
 Console.WriteLine("                     注：如不指定此参数则为自动索引，手动确认安装。");
 Console.WriteLine("");
 Console.WriteLine("    /offlineosdir=   对离线的系统安装安装驱动，例：/offlineosdir=D:\\");
 Console.WriteLine("                     注：对当前系统安装驱动无需使用此参数。");
 Console.WriteLine("");
 Console.WriteLine("    /zippwd=         为驱动包指定解压密码 明文 /zippwd=密码  密文 /zippwd=*密码");
 Console.WriteLine("                     注：此参数仅支持以参数形式指定。");
 Console.WriteLine("");
 Console.WriteLine("    /*zippwd=        加密明文，输出一个加密后的密码");
 Console.WriteLine("");
 Console.WriteLine("    /setdrvdir=      设置驱动目录，程序有默认目录一般是不需要这个的。");
 Console.WriteLine("");
 Console.WriteLine("    /logfile=off      使用此参数不输出日志文件。默认是输出的。");
 Console.WriteLine("");
 Console.WriteLine("生成驱动压缩包的索引文件：");
 Console.WriteLine("     生成此文件能极大提高驱动索引速度，强烈推荐。不生成也不影响安装，但索引驱动包会很慢");
 Console.WriteLine("     注：不以/auto参数运行就显示此选项，需每次添加或更新驱动执行一次。");
 Console.WriteLine("");
 Console.WriteLine("输出离线驱动包支持硬件型号：");
 Console.WriteLine("     注：不以/auto参数运行就显示此选项(需先生成驱动包索引文件)。");
 Console.WriteLine("");
 Console.WriteLine("关于程序驱动压缩包提取说明：");
 Console.WriteLine("     程序所在目录下有\\Res目录，此目录可删除，但不建议。");
 Console.WriteLine("     \\Res\\7z.exe 软件默认用7z解压缩提取，因为他快。");
 Console.WriteLine("     但本程序并不依赖于此，程序有自己的内置代码，如对压缩包有加密需求，请删除7z，避免密码传递暴漏风险。");
 Console.WriteLine("     \\Res\\devcon.exe 程序并不首选此但作为备用，可删除，但不建议。");
 Console.WriteLine("");
 Console.WriteLine("关于程序驱动安装规则：");
 Console.WriteLine("     对当前系统仅安装 未安装驱动的硬件设备 或 较新的驱动 或已安装但存在问题的驱动");
 Console.WriteLine("     对离线系统无此规则。");
 Console.WriteLine("     全局规则，如多个驱动匹配同一设备，则默认选择版本较大的。");
 Console.WriteLine("");
 Console.WriteLine("软件退出代码:");
 Console.WriteLine("0            正常退出/有驱动安装成功(具体日志会在控制台及日志中输出);");
 Console.WriteLine("-1           软件重复运行，多开错误;");
 Console.WriteLine("-2           软件驱动目录不存在;");
 Console.WriteLine("-3           参数指定的离线系统不是完整的系统(乱指定);");
 Console.WriteLine("-4           系统位宽不是x64;");
 Console.WriteLine("1607         系统版本过低(限制对>=1607版本安装驱动);");
 Console.WriteLine("-99          未能枚举到本设备硬件信息;");
 Console.WriteLine("-66          在驱动目录未找到任何驱动包或驱动文件;");
 Console.WriteLine("-88          在驱动包内未索引到本机设备驱动;");
 Console.WriteLine("-9999        索引到了驱动，但0个安装成功;");
